### ISSUE TITLE
Allow to generate the first address without PIN request

### ISSUE THREAD

**Issue by stdevAlDen** [fibercrypto/skywallet-mcu#379]
**Feature description**

Make possible to ask for the first address without asking for the PIN.

**Is your feature request related to a problem? Please describe.**
Check if the hw seed match with other https://github.com/fibercrypto/fibercryptowallet/issues/255

**Additional context**
https://github.com/fibercrypto/fibercryptowallet/issues/255

**Possible implementation**
Just disable PIN protection for the first address.

**Comment by olemis** [comment]
@stdevAlDen but if first address only is requested ... any other subset including `0`-th address must trigger password protection
