### ISSUE TITLE
Enforce code styles with linters

### ISSUE THREAD

**Issue by isaacvr** [fibercrypto/skywallet-mcu#69]
**Feature description**

Normalize code style for clean PR diffs

**Is your feature request related to a problem? Please describe.**
After analyzing some PR's the corresponding patches sometimes differ on whitespace only.

**Describe the solution you'd like**
Diffs could have been smaller if code would have been normalized and rules enforced by a linter

**Possible implementation**

- [x] Choose code style
- [x] Find linters able to enforce that style
- [x] Implement `make lint` target
- [x] Run `make lint` in Travis

**Comment by olemis** [comment]
fixed in 976da66
